## 基础环境
cask "font-maple-mono-normal-nf"
cask "iterm2"
cask "google-chrome"
cask "visual-studio-code"

## 配置ssh
brew "age"
brew "git-delta"
brew "chezmoi"

## 常用工具
brew "starship"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "gh"
brew "lazygit"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "jq"
brew "ripgrep"
brew "tree"
brew "wget"
brew "htop"
brew "lsd"
cask "orbstack"
brew "lazydocker"
cask "ghostty"
cask "stats"
cask "mos"
cask "mac-mouse-fix"
cask "obsidian"

## Flutter开发环境
brew "mise"
brew "cocoapods"

## AI开发环境
brew "uv"
brew "ruff"
brew "python"
brew "pipx"
brew "sqlite"